name: "J'TE VIDÃ‰O"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.85819
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eceee1'
    - '#bbc1a6'
    - '#1b1d18'
    - '#525f4f'
    - '#677f60'
  brandStrength: 0.8125
  lightness: 0.793790637049824
  saturation: 0.75
  rhythmicContrast: 0.4028517175465822
purpose: []
